version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: maxi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sym64maxi
      MYSQL_USER: maxi
      MYSQL_PASSWORD: maxi123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - maxi_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://maxi:maxi123@mysql:3306/sym64maxi?serverVersion=8.0.31&charset=utf8mb4"
    networks:
      - maxi_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - maxi_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"    
    environment:
      PMA_HOST: mysql
      PMA_USER: maxi
      PMA_PASSWORD: maxi123
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - maxi_network

volumes:
  mysql_data:

networks:
  maxi_network:
    driver: bridge